<?php 
defined('BASEPATH') OR exit('No direct script access allowed');

require(APPPATH.'/libraries/REST_Controller.php');

class Api_Contact extends REST_Controller
{
	function user_get($id)
	{
		//respond with information about user
		if(!$id)
		{
			$this->response(NULL, 400);
		}
		$this->load->model('order');
		$user = $this->order->show_student_id($id);
		
		if($user)
		{
			$this->response($user, 200); //200 being the http response
		}
		else
		{
			$this->response(NULL, 404);
		}
	}
	
	function user_put()
	{

	}
	 
	function user_post($id)
	{	
		//update an existing user and respond with a status/error
		$this->load->model('group_model');
		$this->group_model->show_student($id);
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('first_name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
	
	}
	
	function user_delete($id)
	{
	
		//delete a user and respond with a status/errors
		//$id = (int) $this->get('id');
		
		//validate id 
		if($id <= 0)
		{
			//set response and exit
			$this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); //bad request
		}
		
		$this->load->model('group_model');
		$this->group_model->delete_student_id($id);
		$message = array(
			'id' => $id,
			'message' => 'Deleted the resource'
		);
		
		$this->set_response($message, REST_Controller::HTTP_NO_CONTENT);
	}
	
 }
 
?>